name: Suspend stale deploys
on:
  schedule:
    - cron: "1 * * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale-label-fetch@v1.0
      with:
        id: stale-label
        github-token: ${{ secrets.GITHUB_TOKEN }}
        stale-label: 'active-review-app'
        stale-time: '1'
    - name: Get stale numbers
      run: echo "mached PR number ${{ steps.stale-label.outputs.stale-numbers }}"
