name: Suspend stale deploys
on: push

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: akshaysasidrn/stale-label-fetch@v1.1
      id: stale-label
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        stale-label: 'active-review-app'
        stale-time: '1'
        type: 'pull_request'
    - name: Get stale numbers
      run: echo "mached PR number ${{ steps.stale-label.outputs.stale-numbers }}"
